apiVersion: v1
kind: Service
metadata:
  labels:
    app: youtube-feeds
    version: "latest"
  name: youtube-feeds
  namespace: default
spec:
  ports:
  - name: tcp-6003-6003-lstoe
    nodePort: 30000
    port: 6003
    protocol: TCP
    targetPort: 6003
  selector:
    app: youtube-feeds
    version: "latest"
  sessionAffinity: None
  type: LoadBalancer
