apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: youtube-feeds
    version: "latest"
  name: youtube-feeds
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-feeds
      version: "latest"
  template:
    metadata:
      labels:
        app: youtube-feeds
        version: "latest"
      name: youtube-feeds
    spec:
      containers:
      - image: registry.ng.bluemix.net/youtube-feeds/youtube-feeds:latest
        name: youtube-feeds
